version: "3.9"

services:
  bot:
    build: .
    container_name: solana-trading-bot
    env_file:
      - .env
    restart: unless-stopped
    # ports:
    #   - 3000:3000 # not strictly needed unless exposing an HTTP endpoint
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
